/**
 * @file Core2.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core2 (ID=2).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_16_end_back__B_17_init_feed__0; // FIFO_Head_B_16_end_back > B_17_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__3;  // B_17_init_feed_feed > B_17_0_feed size:= 1*uchar defined in Core0
extern char *const B_17_init_feed__B_17_0__0;  // B_17_init_feed > B_17_0 size:= 1*char defined in Core0
extern char *const FIFO_Head_B_37_end_back__B_38_init_feed__0; // FIFO_Head_B_37_end_back > B_38_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__22;  // B_38_init_feed_feed > B_38_0_feed size:= 1*uchar defined in Core0
extern char *const B_38_init_feed__B_38_0__0;  // B_38_init_feed > B_38_0 size:= 1*char defined in Core0
extern char *const set_0__B_0_0__0;  // set_0 > B_0_0 size:= 1*char defined in Core0
extern char *const frk_0__B_0_0__0;  // frk_0 > B_0_0 size:= 1*char defined in Core0
extern uchar *const newPort_00__inB__0;  // frk_0_newPort_00 > B_0_0_inB size:= 1*uchar defined in Core0
extern uchar *const out__feed__0;  // set_0_out > B_0_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1_0_1__0;  // B_0_0_outB > implode_OC_1_inC_inC_1_0_1 size:= 1*uchar defined in Core0
extern uchar *const back__back__1;  // B_0_0_back > B_0_end_back_back size:= 1*uchar defined in Core0
extern char *const B_0_0__B_0_end_back__0;  // B_0_0 > B_0_end_back size:= 1*char defined in Core0
extern char *const B_0_0__implode_OC_1_inC__0;  // B_0_0 > implode_OC_1_inC size:= 1*char defined in Core0
extern char *const B_16_0__B_16_end_back__0;  // B_16_0 > B_16_end_back size:= 1*char defined in Core0
extern uchar *const back__back__2;  // B_16_0_back > B_16_end_back_back size:= 1*uchar defined in Core0
extern char *const B_30_0__implode_OC_6_inC__0;  // B_30_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern char *const B_37_0__B_37_end_back__0;  // B_37_0 > B_37_end_back size:= 1*char defined in Core0
extern uchar *const back__back__20;  // B_37_0_back > B_37_end_back_back size:= 1*uchar defined in Core0
extern char *const B_26_0__implode_OC_6_inC__0;  // B_26_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern char *const B_27_0__implode_OC_6_inC__0;  // B_27_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern char *const B_28_0__implode_OC_6_inC__0;  // B_28_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern char *const B_29_0__implode_OC_6_inC__0;  // B_29_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern char *const B_31_0__implode_OC_6_inC__0;  // B_31_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern uchar *const outB__inC_0__1;  // B_26_0_outB > implode_OC_6_inC_inC_0 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1__1;  // B_27_0_outB > implode_OC_6_inC_inC_1 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_2__1;  // B_28_0_outB > implode_OC_6_inC_inC_2 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_3__1;  // B_29_0_outB > implode_OC_6_inC_inC_3 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_4__1;  // B_30_0_outB > implode_OC_6_inC_inC_4 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_5__1;  // B_31_0_outB > implode_OC_6_inC_inC_5 size:= 1*uchar defined in Core0
extern uchar *const outB__inC__1;  // implode_OC_6_inC_outB > OC_6_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_6_inC__OC_6__0;  // implode_OC_6_inC > OC_6 size:= 6*char defined in Core0
extern char *const B_32_0__implode_OC_7_inC__0;  // B_32_0 > implode_OC_7_inC size:= 1*char defined in Core0
extern char *const B_33_0__implode_OC_7_inC__0;  // B_33_0 > implode_OC_7_inC size:= 1*char defined in Core0
extern char *const B_34_0__implode_OC_7_inC__0;  // B_34_0 > implode_OC_7_inC size:= 1*char defined in Core0
extern char *const B_35_0__implode_OC_7_inC__0;  // B_35_0 > implode_OC_7_inC size:= 1*char defined in Core0
extern char *const B_36_0__implode_OC_7_inC__0;  // B_36_0 > implode_OC_7_inC size:= 1*char defined in Core0
extern char *const B_37_0__implode_OC_7_inC__0;  // B_37_0 > implode_OC_7_inC size:= 1*char defined in Core0
extern uchar *const outB__inC_0__2;  // B_32_0_outB > implode_OC_7_inC_inC_0 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1__2;  // B_33_0_outB > implode_OC_7_inC_inC_1 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_2__2;  // B_34_0_outB > implode_OC_7_inC_inC_2 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_3__2;  // B_35_0_outB > implode_OC_7_inC_inC_3 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_4__2;  // B_36_0_outB > implode_OC_7_inC_inC_4 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_5__2;  // B_37_0_outB > implode_OC_7_inC_inC_5 size:= 1*uchar defined in Core0
extern uchar *const outB__inC__2;  // implode_OC_7_inC_outB > OC_7_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_7_inC__OC_7__0;  // implode_OC_7_inC > OC_7 size:= 6*char defined in Core0

void* computationThread_Core2(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_16_end_back__B_17_init_feed__0, 1, NULL, 0); // 1 * char
  fifoInit(FIFO_Head_B_37_end_back__B_38_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__3, FIFO_Head_B_16_end_back__B_17_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(2, 6); // Core2 > Core6
    sendEnd(); // Core2 > Core6
    fifoPop(feed__feed__22, FIFO_Head_B_37_end_back__B_38_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(2, 11); // Core2 > Core11
    sendEnd(); // Core2 > Core11
    receiveStart(); // Core3 > Core2
    receiveEnd(3, 2); // Core3 > Core2
    receiveStart(); // Core0 > Core2
    receiveEnd(0, 2); // Core0 > Core2
    B(newPort_00__inB__0, out__feed__0, outB__inC_1_0_1__0, back__back__1); // B_0_0

    sendStart(2, 1); // Core2 > Core1
    sendEnd(); // Core2 > Core1
    sendStart(2, 1); // Core2 > Core1
    sendEnd(); // Core2 > Core1
    receiveStart(); // Core4 > Core2
    receiveEnd(4, 2); // Core4 > Core2
    fifoPush(back__back__2, FIFO_Head_B_16_end_back__B_17_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core10 > Core2
    receiveEnd(10, 2); // Core10 > Core2
    receiveStart(); // Core10 > Core2
    receiveEnd(10, 2); // Core10 > Core2
    fifoPush(back__back__20, FIFO_Head_B_37_end_back__B_38_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core13 > Core2
    receiveEnd(13, 2); // Core13 > Core2
    receiveStart(); // Core7 > Core2
    receiveEnd(7, 2); // Core7 > Core2
    receiveStart(); // Core8 > Core2
    receiveEnd(8, 2); // Core8 > Core2
    receiveStart(); // Core9 > Core2
    receiveEnd(9, 2); // Core9 > Core2
    receiveStart(); // Core11 > Core2
    receiveEnd(11, 2); // Core11 > Core2
    // Join implode_OC_6_inC

    {
    }
    sendStart(2, 15); // Core2 > Core15
    sendEnd(); // Core2 > Core15
    receiveStart(); // Core12 > Core2
    receiveEnd(12, 2); // Core12 > Core2
    receiveStart(); // Core13 > Core2
    receiveEnd(13, 2); // Core13 > Core2
    receiveStart(); // Core7 > Core2
    receiveEnd(7, 2); // Core7 > Core2
    receiveStart(); // Core8 > Core2
    receiveEnd(8, 2); // Core8 > Core2
    receiveStart(); // Core9 > Core2
    receiveEnd(9, 2); // Core9 > Core2
    receiveStart(); // Core10 > Core2
    receiveEnd(10, 2); // Core10 > Core2
    // Join implode_OC_7_inC

    {
    }
    sendStart(2, 15); // Core2 > Core15
    sendEnd(); // Core2 > Core15
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

