/**
 * @file Core21.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core21 (ID=21).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_34_end_back__B_35_init_feed__0; // FIFO_Head_B_34_end_back > B_35_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__19;  // B_35_init_feed_feed > B_35_0_feed size:= 1*uchar defined in Core0
extern char *const B_35_init_feed__B_35_0__0;  // B_35_init_feed > B_35_0 size:= 1*char defined in Core0
extern char *const FIFO_Head_OB_5_end_back__OB_6_init_feed__0; // FIFO_Head_OB_5_end_back > OB_6_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__30;  // OB_6_init_feed_feed > OB_6_0_feed size:= 1*uchar defined in Core0
extern char *const frk_0__OB_6_0__0;  // frk_0 > OB_6_0 size:= 2*char defined in Core0
extern uchar *const newPort_6_46__inB__0;  // frk_0_newPort_6_46 > OB_6_0_inB size:= 2*uchar defined in Core0
extern uchar *const outB__out_1__0;  // OB_6_0_outB > implode_jn_end_out_out_out_1 size:= 2*uchar defined in Core0
extern uchar *const back__back__29;  // OB_6_0_back > OB_6_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_6_0__OB_6_end_back__0;  // OB_6_0 > OB_6_end_back size:= 1*char defined in Core0
extern char *const OB_6_0__implode_jn_end_out_out__0;  // OB_6_0 > implode_jn_end_out_out size:= 2*char defined in Core0
extern char *const B_34_0__B_34_end_back__0;  // B_34_0 > B_34_end_back size:= 1*char defined in Core0
extern uchar *const back__back__17;  // B_34_0_back > B_34_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_5_0__OB_5_end_back__0;  // OB_5_0 > OB_5_end_back size:= 1*char defined in Core0
extern uchar *const back__back__28;  // OB_5_0_back > OB_5_end_back_back size:= 1*uchar defined in Core0

void* computationThread_Core21(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_34_end_back__B_35_init_feed__0, 1, NULL, 0); // 1 * char
  fifoInit(FIFO_Head_OB_5_end_back__OB_6_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__19, FIFO_Head_B_34_end_back__B_35_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(21, 8); // Core21 > Core8
    sendEnd(); // Core21 > Core8
    fifoPop(feed__feed__30, FIFO_Head_OB_5_end_back__OB_6_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core0 > Core21
    receiveEnd(0, 21); // Core0 > Core21
    B(newPort_6_46__inB__0, feed__feed__30, outB__out_1__0, back__back__29); // OB_6_0

    sendStart(21, 22); // Core21 > Core22
    sendEnd(); // Core21 > Core22
    sendStart(21, 20); // Core21 > Core20
    sendEnd(); // Core21 > Core20
    receiveStart(); // Core7 > Core21
    receiveEnd(7, 21); // Core7 > Core21
    fifoPush(back__back__17, FIFO_Head_B_34_end_back__B_35_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core20 > Core21
    receiveEnd(20, 21); // Core20 > Core21
    fifoPush(back__back__28, FIFO_Head_OB_5_end_back__OB_6_init_feed__0, 1, NULL, 0); // 1 * char
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

