/**
 * @file Core19.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core19 (ID=19).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_32_end_back__B_33_init_feed__0; // FIFO_Head_B_32_end_back > B_33_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__17;  // B_33_init_feed_feed > B_33_0_feed size:= 1*uchar defined in Core0
extern char *const B_33_init_feed__B_33_0__0;  // B_33_init_feed > B_33_0 size:= 1*char defined in Core0
extern char *const FIFO_Head_OB_8_end_back__OB_9_init_feed__0; // FIFO_Head_OB_8_end_back > OB_9_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__33;  // OB_9_init_feed_feed > OB_9_0_feed size:= 1*uchar defined in Core0
extern char *const frk_0__OB_9_0__0;  // frk_0 > OB_9_0 size:= 2*char defined in Core0
extern uchar *const newPort_9_49__inB__0;  // frk_0_newPort_9_49 > OB_9_0_inB size:= 2*uchar defined in Core0
extern uchar *const outB__out_4__0;  // OB_9_0_outB > implode_jn_end_out_out_out_4 size:= 2*uchar defined in Core0
extern void *const back__in__0;  // OB_9_0_back > get_0_in size:= 1*void defined in Core0
extern char *const OB_9_0__get_0__0;  // OB_9_0 > get_0 size:= 1*char defined in Core0
extern char *const OB_9_0__implode_jn_end_out_out__0;  // OB_9_0 > implode_jn_end_out_out size:= 2*char defined in Core0
extern char *const A_0__implode_A_end_outA_outA__0;  // A_0 > implode_A_end_outA_outA size:= 20*char defined in Core0
extern char *const A_1__implode_A_end_outA_outA__0;  // A_1 > implode_A_end_outA_outA size:= 20*char defined in Core0
extern char *const A_2__implode_A_end_outA_outA__0;  // A_2 > implode_A_end_outA_outA size:= 20*char defined in Core0
extern uchar *const outA__outA_0__0;  // A_0_outA > implode_A_end_outA_outA_outA_0 size:= 20*uchar defined in Core0
extern uchar *const outA__outA_1__0;  // A_1_outA > implode_A_end_outA_outA_outA_1 size:= 20*uchar defined in Core0
extern uchar *const outA__outA_2__0;  // A_2_outA > implode_A_end_outA_outA_outA_2 size:= 20*uchar defined in Core0
extern uchar *const outA__outA__0;  // implode_A_end_outA_outA_outA > A_end_outA_outA size:= 60*uchar defined in Core0
extern char *const implode_A_end_outA_outA__A_end_outA__0; // implode_A_end_outA_outA > A_end_outA size:= 60*char defined in Core0
extern char *const B_32_0__B_32_end_back__0;  // B_32_0 > B_32_end_back size:= 1*char defined in Core0
extern uchar *const back__back__15;  // B_32_0_back > B_32_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_8_0__OB_8_end_back__0;  // OB_8_0 > OB_8_end_back size:= 1*char defined in Core0
extern uchar *const back__back__31;  // OB_8_0_back > OB_8_end_back_back size:= 1*uchar defined in Core0

void* computationThread_Core19(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_32_end_back__B_33_init_feed__0, 1, NULL, 0); // 1 * char
  fifoInit(FIFO_Head_OB_8_end_back__OB_9_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__17, FIFO_Head_B_32_end_back__B_33_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(19, 13); // Core19 > Core13
    sendEnd(); // Core19 > Core13
    fifoPop(feed__feed__33, FIFO_Head_OB_8_end_back__OB_9_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core0 > Core19
    receiveEnd(0, 19); // Core0 > Core19
    B(newPort_9_49__inB__0, feed__feed__33, outB__out_4__0, back__in__0); // OB_9_0

    sendStart(19, 18); // Core19 > Core18
    sendEnd(); // Core19 > Core18
    sendStart(19, 20); // Core19 > Core20
    sendEnd(); // Core19 > Core20
    receiveStart(); // Core5 > Core19
    receiveEnd(5, 19); // Core5 > Core19
    receiveStart(); // Core3 > Core19
    receiveEnd(3, 19); // Core3 > Core19
    receiveStart(); // Core4 > Core19
    receiveEnd(4, 19); // Core4 > Core19
    // Join implode_A_end_outA_outA

    {
    }
    sendStart(19, 0); // Core19 > Core0
    sendEnd(); // Core19 > Core0
    receiveStart(); // Core12 > Core19
    receiveEnd(12, 19); // Core12 > Core19
    fifoPush(back__back__15, FIFO_Head_B_32_end_back__B_33_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core23 > Core19
    receiveEnd(23, 19); // Core23 > Core19
    fifoPush(back__back__31, FIFO_Head_OB_8_end_back__OB_9_init_feed__0, 1, NULL, 0); // 1 * char
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

