/**
 * @file Core18.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core18 (ID=18).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif
extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_31_end_back__B_32_init_feed__0; // FIFO_Head_B_31_end_back > B_32_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__16;  // B_32_init_feed_feed > B_32_0_feed size:= 1*uchar defined in Core0
extern char *const B_32_init_feed__B_32_0__0;  // B_32_init_feed > B_32_0 size:= 1*char defined in Core0
extern char *const OB_4_init_feed__OB_4_0__0;  // OB_4_init_feed > OB_4_0 size:= 1*char defined in Core0
extern char *const frk_0__OB_4_0__0;  // frk_0 > OB_4_0 size:= 2*char defined in Core0
extern uchar *const newPort_4_44__inB__0;  // frk_0_newPort_4_44 > OB_4_0_inB size:= 2*uchar defined in Core0
extern uchar *const feed__feed__28;  // OB_4_init_feed_feed > OB_4_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_2__4;  // OB_4_0_outB > implode_OC_9_inC_inC_2 size:= 2*uchar defined in Core0
extern uchar *const back__back__27;  // OB_4_0_back > OB_4_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_4_0__OB_4_end_back__0;  // OB_4_0 > OB_4_end_back size:= 1*char defined in Core0
extern char *const OB_4_0__implode_OC_9_inC__0;  // OB_4_0 > implode_OC_9_inC size:= 2*char defined in Core0
extern char *const B_31_0__B_31_end_back__0;  // B_31_0 > B_31_end_back size:= 1*char defined in Core0
extern uchar *const back__back__14;  // B_31_0_back > B_31_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_9_0__get_0__0;  // OB_9_0 > get_0 size:= 1*char defined in Core0
extern void *const back__in__0;  // OB_9_0_back > get_0_in size:= 1*void defined in Core0

void* computationThread_Core18(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_back__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_back__in__0);
#endif
  // Initialisation(s)

  fifoInit(FIFO_Head_B_31_end_back__B_32_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__16, FIFO_Head_B_31_end_back__B_32_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(18, 12); // Core18 > Core12
    sendEnd(); // Core18 > Core12
    receiveStart(); // Core10 > Core18
    receiveEnd(10, 18); // Core10 > Core18
    receiveStart(); // Core0 > Core18
    receiveEnd(0, 18); // Core0 > Core18
    B(newPort_4_44__inB__0, feed__feed__28, outB__inC_2__4, back__back__27); // OB_4_0

    sendStart(18, 20); // Core18 > Core20
    sendEnd(); // Core18 > Core20
    sendStart(18, 15); // Core18 > Core15
    sendEnd(); // Core18 > Core15
    receiveStart(); // Core11 > Core18
    receiveEnd(11, 18); // Core11 > Core18
    fifoPush(back__back__14, FIFO_Head_B_31_end_back__B_32_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core19 > Core18
    receiveEnd(19, 18); // Core19 > Core18
    get(back__in__0); // get_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_back__in__0,(char *)back__in__0, 1);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_back__in__0);
	printf("preesm_md5_back__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

