/**
 * @file Core12.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core12 (ID=12).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_25_end_back__B_26_init_feed__0; // FIFO_Head_B_25_end_back > B_26_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__10;  // B_26_init_feed_feed > B_26_0_feed size:= 1*uchar defined in Core0
extern char *const B_26_init_feed__B_26_0__0;  // B_26_init_feed > B_26_0 size:= 1*char defined in Core0
extern char *const B_25_init_feed__B_25_0__0;  // B_25_init_feed > B_25_0 size:= 1*char defined in Core0
extern char *const frk_0__B_25_0__0;  // frk_0 > B_25_0 size:= 1*char defined in Core0
extern uchar *const newPort25_25__inB__0;  // frk_0_newPort25_25 > B_25_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__9;  // B_25_init_feed_feed > B_25_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_5__0;  // B_25_0_outB > implode_OC_5_inC_inC_5 size:= 1*uchar defined in Core0
extern uchar *const back__back__8;  // B_25_0_back > B_25_end_back_back size:= 1*uchar defined in Core0
extern char *const B_25_0__implode_OC_5_inC__0;  // B_25_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern char *const B_32_init_feed__B_32_0__0;  // B_32_init_feed > B_32_0 size:= 1*char defined in Core0
extern char *const frk_0__B_32_0__0;  // frk_0 > B_32_0 size:= 1*char defined in Core0
extern uchar *const newPort32_32__inB__0;  // frk_0_newPort32_32 > B_32_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__16;  // B_32_init_feed_feed > B_32_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_0__2;  // B_32_0_outB > implode_OC_7_inC_inC_0 size:= 1*uchar defined in Core0
extern uchar *const back__back__15;  // B_32_0_back > B_32_end_back_back size:= 1*uchar defined in Core0
extern char *const B_32_0__B_32_end_back__0;  // B_32_0 > B_32_end_back size:= 1*char defined in Core0
extern char *const B_32_0__implode_OC_7_inC__0;  // B_32_0 > implode_OC_7_inC size:= 1*char defined in Core0
extern char *const B_39_init_feed__B_39_0__0;  // B_39_init_feed > B_39_0 size:= 1*char defined in Core0
extern char *const frk_0__B_39_0__0;  // frk_0 > B_39_0 size:= 1*char defined in Core0
extern uchar *const newPort39_39__inB__0;  // frk_0_newPort39_39 > B_39_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__23;  // B_39_init_feed_feed > B_39_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1__3;  // B_39_0_outB > implode_OC_8_inC_inC_1 size:= 1*uchar defined in Core0
extern uchar *const back__back__22;  // B_39_0_back > B_39_end_back_back size:= 1*uchar defined in Core0
extern char *const B_39_0__B_39_end_back__0;  // B_39_0 > B_39_end_back size:= 1*char defined in Core0
extern char *const B_39_0__implode_OC_8_inC__0;  // B_39_0 > implode_OC_8_inC size:= 1*char defined in Core0

void* computationThread_Core12(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_25_end_back__B_26_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__10, FIFO_Head_B_25_end_back__B_26_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(12, 13); // Core12 > Core13
    sendEnd(); // Core12 > Core13
    receiveStart(); // Core11 > Core12
    receiveEnd(11, 12); // Core11 > Core12
    receiveStart(); // Core0 > Core12
    receiveEnd(0, 12); // Core0 > Core12
    B(newPort25_25__inB__0, feed__feed__9, outB__inC_5__0, back__back__8); // B_25_0

    sendStart(12, 3); // Core12 > Core3
    sendEnd(); // Core12 > Core3
    receiveStart(); // Core18 > Core12
    receiveEnd(18, 12); // Core18 > Core12
    receiveStart(); // Core0 > Core12
    receiveEnd(0, 12); // Core0 > Core12
    B(newPort32_32__inB__0, feed__feed__16, outB__inC_0__2, back__back__15); // B_32_0

    sendStart(12, 19); // Core12 > Core19
    sendEnd(); // Core12 > Core19
    sendStart(12, 2); // Core12 > Core2
    sendEnd(); // Core12 > Core2
    receiveStart(); // Core4 > Core12
    receiveEnd(4, 12); // Core4 > Core12
    receiveStart(); // Core0 > Core12
    receiveEnd(0, 12); // Core0 > Core12
    B(newPort39_39__inB__0, feed__feed__23, outB__inC_1__3, back__back__22); // B_39_0

    sendStart(12, 5); // Core12 > Core5
    sendEnd(); // Core12 > Core5
    sendStart(12, 3); // Core12 > Core3
    sendEnd(); // Core12 > Core3
    fifoPush(back__back__8, FIFO_Head_B_25_end_back__B_26_init_feed__0, 1, NULL, 0); // 1 * char
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

