/**
 * @file Core14.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core14 (ID=14).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif
extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_27_end_back__B_28_init_feed__0; // FIFO_Head_B_27_end_back > B_28_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__12;  // B_28_init_feed_feed > B_28_0_feed size:= 1*uchar defined in Core0
extern char *const B_28_init_feed__B_28_0__0;  // B_28_init_feed > B_28_0 size:= 1*char defined in Core0
extern char *const OB_0_init_feed__OB_0_0__0;  // OB_0_init_feed > OB_0_0 size:= 1*char defined in Core0
extern char *const frk_0__OB_0_0__0;  // frk_0 > OB_0_0 size:= 2*char defined in Core0
extern uchar *const newPort_0_41__inB__0;  // frk_0_newPort_0_41 > OB_0_0_inB size:= 2*uchar defined in Core0
extern uchar *const feed__feed__24;  // OB_0_init_feed_feed > OB_0_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_2__3;  // OB_0_0_outB > implode_OC_8_inC_inC_2 size:= 2*uchar defined in Core0
extern uchar *const back__back__24;  // OB_0_0_back > OB_0_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_0_0__OB_0_end_back__0;  // OB_0_0 > OB_0_end_back size:= 1*char defined in Core0
extern char *const OB_0_0__implode_OC_8_inC__0;  // OB_0_0 > implode_OC_8_inC size:= 2*char defined in Core0
extern char *const B_27_0__B_27_end_back__0;  // B_27_0 > B_27_end_back size:= 1*char defined in Core0
extern uchar *const back__back__10;  // B_27_0_back > B_27_end_back_back size:= 1*uchar defined in Core0
extern char *const implode_OC_1_inC__OC_1__0;  // implode_OC_1_inC > OC_1 size:= 6*char defined in Core0
extern uchar *const inC__inC__1;  // implode_OC_1_inC_inC > OC_1_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_2_inC__OC_2__0;  // implode_OC_2_inC > OC_2 size:= 6*char defined in Core0
extern uchar *const outB__inC__5;  // implode_OC_2_inC_outB > OC_2_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_3_inC__OC_3__0;  // implode_OC_3_inC > OC_3 size:= 6*char defined in Core0
extern uchar *const outB__inC__7;  // implode_OC_3_inC_outB > OC_3_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_4_inC__OC_4__0;  // implode_OC_4_inC > OC_4 size:= 6*char defined in Core0
extern uchar *const outB__inC__6;  // implode_OC_4_inC_outB > OC_4_inC size:= 6*uchar defined in Core0

void* computationThread_Core14(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_inC__inC__1;
	PREESM_MD5_Init(&preesm_md5_ctx_inC__inC__1);
	PREESM_MD5_CTX preesm_md5_ctx_outB__inC__5;
	PREESM_MD5_Init(&preesm_md5_ctx_outB__inC__5);
	PREESM_MD5_CTX preesm_md5_ctx_outB__inC__7;
	PREESM_MD5_Init(&preesm_md5_ctx_outB__inC__7);
	PREESM_MD5_CTX preesm_md5_ctx_outB__inC__6;
	PREESM_MD5_Init(&preesm_md5_ctx_outB__inC__6);
#endif
  // Initialisation(s)

  fifoInit(FIFO_Head_B_27_end_back__B_28_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__12, FIFO_Head_B_27_end_back__B_28_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(14, 8); // Core14 > Core8
    sendEnd(); // Core14 > Core8
    receiveStart(); // Core5 > Core14
    receiveEnd(5, 14); // Core5 > Core14
    receiveStart(); // Core0 > Core14
    receiveEnd(0, 14); // Core0 > Core14
    B(newPort_0_41__inB__0, feed__feed__24, outB__inC_2__3, back__back__24); // OB_0_0

    sendStart(14, 7); // Core14 > Core7
    sendEnd(); // Core14 > Core7
    sendStart(14, 3); // Core14 > Core3
    sendEnd(); // Core14 > Core3
    receiveStart(); // Core7 > Core14
    receiveEnd(7, 14); // Core7 > Core14
    fifoPush(back__back__10, FIFO_Head_B_27_end_back__B_28_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core1 > Core14
    receiveEnd(1, 14); // Core1 > Core14
    C(inC__inC__1); // OC_1
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_inC__inC__1,(char *)inC__inC__1, 6);
		#endif

    receiveStart(); // Core1 > Core14
    receiveEnd(1, 14); // Core1 > Core14
    C(outB__inC__5); // OC_2
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_outB__inC__5,(char *)outB__inC__5, 6);
		#endif

    receiveStart(); // Core1 > Core14
    receiveEnd(1, 14); // Core1 > Core14
    C(outB__inC__7); // OC_3
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_outB__inC__7,(char *)outB__inC__7, 6);
		#endif

    receiveStart(); // Core0 > Core14
    receiveEnd(0, 14); // Core0 > Core14
    C(outB__inC__6); // OC_4
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_outB__inC__6,(char *)outB__inC__6, 6);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_inC__inC__1);
	printf("preesm_md5_inC__inC__1 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_outB__inC__5);
	printf("preesm_md5_outB__inC__5 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_outB__inC__7);
	printf("preesm_md5_outB__inC__7 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_outB__inC__6);
	printf("preesm_md5_outB__inC__6 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

