/**
 * @file Core13.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core13 (ID=13).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_26_end_back__B_27_init_feed__0; // FIFO_Head_B_26_end_back > B_27_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__11;  // B_27_init_feed_feed > B_27_0_feed size:= 1*uchar defined in Core0
extern char *const B_27_init_feed__B_27_0__0;  // B_27_init_feed > B_27_0 size:= 1*char defined in Core0
extern char *const B_26_init_feed__B_26_0__0;  // B_26_init_feed > B_26_0 size:= 1*char defined in Core0
extern char *const frk_0__B_26_0__0;  // frk_0 > B_26_0 size:= 1*char defined in Core0
extern uchar *const newPort26_26__inB__0;  // frk_0_newPort26_26 > B_26_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__10;  // B_26_init_feed_feed > B_26_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_0__1;  // B_26_0_outB > implode_OC_6_inC_inC_0 size:= 1*uchar defined in Core0
extern uchar *const back__back__9;  // B_26_0_back > B_26_end_back_back size:= 1*uchar defined in Core0
extern char *const B_26_0__implode_OC_6_inC__0;  // B_26_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern char *const B_33_init_feed__B_33_0__0;  // B_33_init_feed > B_33_0 size:= 1*char defined in Core0
extern char *const frk_0__B_33_0__0;  // frk_0 > B_33_0 size:= 1*char defined in Core0
extern uchar *const newPort33_33__inB__0;  // frk_0_newPort33_33 > B_33_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__17;  // B_33_init_feed_feed > B_33_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1__2;  // B_33_0_outB > implode_OC_7_inC_inC_1 size:= 1*uchar defined in Core0
extern uchar *const back__back__16;  // B_33_0_back > B_33_end_back_back size:= 1*uchar defined in Core0
extern char *const B_33_0__B_33_end_back__0;  // B_33_0 > B_33_end_back size:= 1*char defined in Core0
extern char *const B_33_0__implode_OC_7_inC__0;  // B_33_0 > implode_OC_7_inC size:= 1*char defined in Core0

void* computationThread_Core13(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_26_end_back__B_27_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__11, FIFO_Head_B_26_end_back__B_27_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(13, 7); // Core13 > Core7
    sendEnd(); // Core13 > Core7
    receiveStart(); // Core12 > Core13
    receiveEnd(12, 13); // Core12 > Core13
    receiveStart(); // Core0 > Core13
    receiveEnd(0, 13); // Core0 > Core13
    B(newPort26_26__inB__0, feed__feed__10, outB__inC_0__1, back__back__9); // B_26_0

    sendStart(13, 2); // Core13 > Core2
    sendEnd(); // Core13 > Core2
    receiveStart(); // Core19 > Core13
    receiveEnd(19, 13); // Core19 > Core13
    receiveStart(); // Core0 > Core13
    receiveEnd(0, 13); // Core0 > Core13
    B(newPort33_33__inB__0, feed__feed__17, outB__inC_1__2, back__back__16); // B_33_0

    sendStart(13, 20); // Core13 > Core20
    sendEnd(); // Core13 > Core20
    sendStart(13, 2); // Core13 > Core2
    sendEnd(); // Core13 > Core2
    fifoPush(back__back__9, FIFO_Head_B_26_end_back__B_27_init_feed__0, 1, NULL, 0); // 1 * char
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

