/**
 * @file Core23.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core23 (ID=23).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_36_end_back__B_37_init_feed__0; // FIFO_Head_B_36_end_back > B_37_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__21;  // B_37_init_feed_feed > B_37_0_feed size:= 1*uchar defined in Core0
extern char *const B_37_init_feed__B_37_0__0;  // B_37_init_feed > B_37_0 size:= 1*char defined in Core0
extern char *const FIFO_Head_OB_7_end_back__OB_8_init_feed__0; // FIFO_Head_OB_7_end_back > OB_8_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__32;  // OB_8_init_feed_feed > OB_8_0_feed size:= 1*uchar defined in Core0
extern char *const frk_0__OB_8_0__0;  // frk_0 > OB_8_0 size:= 2*char defined in Core0
extern uchar *const newPort_8_48__inB__0;  // frk_0_newPort_8_48 > OB_8_0_inB size:= 2*uchar defined in Core0
extern uchar *const outB__out_3__0;  // OB_8_0_outB > implode_jn_end_out_out_out_3 size:= 2*uchar defined in Core0
extern uchar *const back__back__31;  // OB_8_0_back > OB_8_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_8_0__OB_8_end_back__0;  // OB_8_0 > OB_8_end_back size:= 1*char defined in Core0
extern char *const OB_8_0__implode_jn_end_out_out__0;  // OB_8_0 > implode_jn_end_out_out size:= 2*char defined in Core0
extern char *const B_36_0__B_36_end_back__0;  // B_36_0 > B_36_end_back size:= 1*char defined in Core0
extern uchar *const back__back__19;  // B_36_0_back > B_36_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_7_0__OB_7_end_back__0;  // OB_7_0 > OB_7_end_back size:= 1*char defined in Core0
extern uchar *const back__back__30;  // OB_7_0_back > OB_7_end_back_back size:= 1*uchar defined in Core0

void* computationThread_Core23(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_36_end_back__B_37_init_feed__0, 1, NULL, 0); // 1 * char
  fifoInit(FIFO_Head_OB_7_end_back__OB_8_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__21, FIFO_Head_B_36_end_back__B_37_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(23, 10); // Core23 > Core10
    sendEnd(); // Core23 > Core10
    fifoPop(feed__feed__32, FIFO_Head_OB_7_end_back__OB_8_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core0 > Core23
    receiveEnd(0, 23); // Core0 > Core23
    B(newPort_8_48__inB__0, feed__feed__32, outB__out_3__0, back__back__31); // OB_8_0

    sendStart(23, 19); // Core23 > Core19
    sendEnd(); // Core23 > Core19
    sendStart(23, 20); // Core23 > Core20
    sendEnd(); // Core23 > Core20
    receiveStart(); // Core9 > Core23
    receiveEnd(9, 23); // Core9 > Core23
    fifoPush(back__back__19, FIFO_Head_B_36_end_back__B_37_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core22 > Core23
    receiveEnd(22, 23); // Core22 > Core23
    fifoPush(back__back__30, FIFO_Head_OB_7_end_back__OB_8_init_feed__0, 1, NULL, 0); // 1 * char
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

