/**
 * @file Core16.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core16 (ID=16).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif
extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_29_end_back__B_30_init_feed__0; // FIFO_Head_B_29_end_back > B_30_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__14;  // B_30_init_feed_feed > B_30_0_feed size:= 1*uchar defined in Core0
extern char *const B_30_init_feed__B_30_0__0;  // B_30_init_feed > B_30_0 size:= 1*char defined in Core0
extern char *const OB_2_init_feed__OB_2_0__0;  // OB_2_init_feed > OB_2_0 size:= 1*char defined in Core0
extern char *const frk_0__OB_2_0__0;  // frk_0 > OB_2_0 size:= 2*char defined in Core0
extern uchar *const newPort_2_42__inB__0;  // frk_0_newPort_2_42 > OB_2_0_inB size:= 2*uchar defined in Core0
extern uchar *const feed__feed__26;  // OB_2_init_feed_feed > OB_2_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_0__4;  // OB_2_0_outB > implode_OC_9_inC_inC_0 size:= 2*uchar defined in Core0
extern uchar *const back__back__25;  // OB_2_0_back > OB_2_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_2_0__OB_2_end_back__0;  // OB_2_0 > OB_2_end_back size:= 1*char defined in Core0
extern char *const OB_2_0__implode_OC_9_inC__0;  // OB_2_0 > implode_OC_9_inC size:= 2*char defined in Core0
extern char *const explode_OC_init_inC_inC__OC_0__0;  // explode_OC_init_inC_inC > OC_0 size:= 6*char defined in Core0
extern uchar *const inC_0__inC__0;  // explode_OC_init_inC_inC_inC_0 > OC_0_inC size:= 6*uchar defined in Core0
extern char *const B_29_0__B_29_end_back__0;  // B_29_0 > B_29_end_back size:= 1*char defined in Core0
extern uchar *const back__back__12;  // B_29_0_back > B_29_end_back_back size:= 1*uchar defined in Core0
extern char *const implode_OC_8_inC__OC_8__0;  // implode_OC_8_inC > OC_8 size:= 6*char defined in Core0
extern uchar *const outB__inC__3;  // implode_OC_8_inC_outB > OC_8_inC size:= 6*uchar defined in Core0

void* computationThread_Core16(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_inC_0__inC__0;
	PREESM_MD5_Init(&preesm_md5_ctx_inC_0__inC__0);
	PREESM_MD5_CTX preesm_md5_ctx_outB__inC__3;
	PREESM_MD5_Init(&preesm_md5_ctx_outB__inC__3);
#endif
  // Initialisation(s)

  fifoInit(FIFO_Head_B_29_end_back__B_30_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__14, FIFO_Head_B_29_end_back__B_30_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(16, 10); // Core16 > Core10
    sendEnd(); // Core16 > Core10
    receiveStart(); // Core8 > Core16
    receiveEnd(8, 16); // Core8 > Core16
    receiveStart(); // Core0 > Core16
    receiveEnd(0, 16); // Core0 > Core16
    B(newPort_2_42__inB__0, feed__feed__26, outB__inC_0__4, back__back__25); // OB_2_0

    sendStart(16, 9); // Core16 > Core9
    sendEnd(); // Core16 > Core9
    sendStart(16, 15); // Core16 > Core15
    sendEnd(); // Core16 > Core15
    receiveStart(); // Core5 > Core16
    receiveEnd(5, 16); // Core5 > Core16
    C(inC_0__inC__0); // OC_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_inC_0__inC__0,(char *)inC_0__inC__0, 6);
		#endif

    receiveStart(); // Core9 > Core16
    receiveEnd(9, 16); // Core9 > Core16
    fifoPush(back__back__12, FIFO_Head_B_29_end_back__B_30_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core3 > Core16
    receiveEnd(3, 16); // Core3 > Core16
    C(outB__inC__3); // OC_8
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_outB__inC__3,(char *)outB__inC__3, 6);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_inC_0__inC__0);
	printf("preesm_md5_inC_0__inC__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_outB__inC__3);
	printf("preesm_md5_outB__inC__3 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

