/**
 * @file Core3.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core3 (ID=3).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern uchar *const outA__outA_1__0;  // A_1_outA > implode_A_end_outA_outA_outA_1 size:= 20*uchar defined in Core0
extern char *const A_1__implode_A_end_outA_outA__0;  // A_1 > implode_A_end_outA_outA size:= 20*char defined in Core0
extern uchar *const out__feed__0;  // set_0_out > B_0_0_feed size:= 1*uchar defined in Core0
extern char *const set_0__B_0_0__0;  // set_0 > B_0_0 size:= 1*char defined in Core0
extern char *const B_20_0__implode_OC_5_inC__0;  // B_20_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern char *const B_21_0__implode_OC_5_inC__0;  // B_21_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern char *const B_22_0__implode_OC_5_inC__0;  // B_22_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern char *const B_23_0__implode_OC_5_inC__0;  // B_23_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern char *const B_24_0__implode_OC_5_inC__0;  // B_24_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern char *const B_25_0__implode_OC_5_inC__0;  // B_25_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern uchar *const outB__inC_0__0;  // B_20_0_outB > implode_OC_5_inC_inC_0 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1__0;  // B_21_0_outB > implode_OC_5_inC_inC_1 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_2__0;  // B_22_0_outB > implode_OC_5_inC_inC_2 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_3__0;  // B_23_0_outB > implode_OC_5_inC_inC_3 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_4__0;  // B_24_0_outB > implode_OC_5_inC_inC_4 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_5__0;  // B_25_0_outB > implode_OC_5_inC_inC_5 size:= 1*uchar defined in Core0
extern uchar *const outB__inC__0;  // implode_OC_5_inC_outB > OC_5_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_5_inC__OC_5__0;  // implode_OC_5_inC > OC_5 size:= 6*char defined in Core0
extern char *const B_38_0__implode_OC_8_inC__0;  // B_38_0 > implode_OC_8_inC size:= 1*char defined in Core0
extern char *const B_39_0__implode_OC_8_inC__0;  // B_39_0 > implode_OC_8_inC size:= 1*char defined in Core0
extern char *const OB_0_0__implode_OC_8_inC__0;  // OB_0_0 > implode_OC_8_inC size:= 2*char defined in Core0
extern char *const OB_1_0__implode_OC_8_inC__0;  // OB_1_0 > implode_OC_8_inC size:= 2*char defined in Core0
extern uchar *const outB__inC_0__3;  // B_38_0_outB > implode_OC_8_inC_inC_0 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1__3;  // B_39_0_outB > implode_OC_8_inC_inC_1 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_2__3;  // OB_0_0_outB > implode_OC_8_inC_inC_2 size:= 2*uchar defined in Core0
extern uchar *const outB__inC_3__3;  // OB_1_0_outB > implode_OC_8_inC_inC_3 size:= 2*uchar defined in Core0
extern uchar *const outB__inC__3;  // implode_OC_8_inC_outB > OC_8_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_8_inC__OC_8__0;  // implode_OC_8_inC > OC_8 size:= 6*char defined in Core0

void* computationThread_Core3(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    A(outA__outA_1__0); // A_1

    sendStart(3, 19); // Core3 > Core19
    sendEnd(); // Core3 > Core19
    set(out__feed__0); // set_0

    sendStart(3, 2); // Core3 > Core2
    sendEnd(); // Core3 > Core2
    receiveStart(); // Core7 > Core3
    receiveEnd(7, 3); // Core7 > Core3
    receiveStart(); // Core8 > Core3
    receiveEnd(8, 3); // Core8 > Core3
    receiveStart(); // Core9 > Core3
    receiveEnd(9, 3); // Core9 > Core3
    receiveStart(); // Core10 > Core3
    receiveEnd(10, 3); // Core10 > Core3
    receiveStart(); // Core11 > Core3
    receiveEnd(11, 3); // Core11 > Core3
    receiveStart(); // Core12 > Core3
    receiveEnd(12, 3); // Core12 > Core3
    // Join implode_OC_5_inC

    {
    }
    sendStart(3, 15); // Core3 > Core15
    sendEnd(); // Core3 > Core15
    receiveStart(); // Core11 > Core3
    receiveEnd(11, 3); // Core11 > Core3
    receiveStart(); // Core12 > Core3
    receiveEnd(12, 3); // Core12 > Core3
    receiveStart(); // Core14 > Core3
    receiveEnd(14, 3); // Core14 > Core3
    receiveStart(); // Core15 > Core3
    receiveEnd(15, 3); // Core15 > Core3
    // Join implode_OC_8_inC

    {
    }
    sendStart(3, 16); // Core3 > Core16
    sendEnd(); // Core3 > Core16
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

