/**
 * @file Core4.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core4 (ID=4).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern uchar *const outA__outA_2__0;  // A_2_outA > implode_A_end_outA_outA_outA_2 size:= 20*uchar defined in Core0
extern char *const A_2__implode_A_end_outA_outA__0;  // A_2 > implode_A_end_outA_outA size:= 20*char defined in Core0
extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_15_end_back__B_16_init_feed__0; // FIFO_Head_B_15_end_back > B_16_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__2;  // B_16_init_feed_feed > B_16_0_feed size:= 1*uchar defined in Core0
extern char *const FIFO_Head_B_38_end_back__B_39_init_feed__0; // FIFO_Head_B_38_end_back > B_39_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__23;  // B_39_init_feed_feed > B_39_0_feed size:= 1*uchar defined in Core0
extern char *const B_39_init_feed__B_39_0__0;  // B_39_init_feed > B_39_0 size:= 1*char defined in Core0
extern char *const frk_0__B_16_0__0;  // frk_0 > B_16_0 size:= 1*char defined in Core0
extern uchar *const newPort16_16__inB__0;  // frk_0_newPort16_16 > B_16_0_inB size:= 1*uchar defined in Core0
extern uchar *const outB__inC_2__6;  // B_16_0_outB > implode_OC_4_inC_inC_2 size:= 1*uchar defined in Core0
extern uchar *const back__back__2;  // B_16_0_back > B_16_end_back_back size:= 1*uchar defined in Core0
extern char *const B_16_0__B_16_end_back__0;  // B_16_0 > B_16_end_back size:= 1*char defined in Core0
extern char *const B_16_0__implode_OC_4_inC__0;  // B_16_0 > implode_OC_4_inC size:= 1*char defined in Core0
extern char *const B_38_0__B_38_end_back__0;  // B_38_0 > B_38_end_back size:= 1*char defined in Core0
extern uchar *const back__back__21;  // B_38_0_back > B_38_end_back_back size:= 1*uchar defined in Core0
extern char *const B_15_0__B_15_end_back__0;  // B_15_0 > B_15_end_back size:= 1*char defined in Core0
extern uchar *const back__back__33;  // B_15_0_back > B_15_end_back_back size:= 1*uchar defined in Core0

void* computationThread_Core4(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_15_end_back__B_16_init_feed__0, 1, NULL, 0); // 1 * char
  fifoInit(FIFO_Head_B_38_end_back__B_39_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    A(outA__outA_2__0); // A_2

    sendStart(4, 19); // Core4 > Core19
    sendEnd(); // Core4 > Core19
    fifoPop(feed__feed__2, FIFO_Head_B_15_end_back__B_16_init_feed__0, 1, NULL, 0); // 1 * char
    fifoPop(feed__feed__23, FIFO_Head_B_38_end_back__B_39_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(4, 12); // Core4 > Core12
    sendEnd(); // Core4 > Core12
    receiveStart(); // Core0 > Core4
    receiveEnd(0, 4); // Core0 > Core4
    B(newPort16_16__inB__0, feed__feed__2, outB__inC_2__6, back__back__2); // B_16_0

    sendStart(4, 2); // Core4 > Core2
    sendEnd(); // Core4 > Core2
    sendStart(4, 0); // Core4 > Core0
    sendEnd(); // Core4 > Core0
    receiveStart(); // Core11 > Core4
    receiveEnd(11, 4); // Core11 > Core4
    fifoPush(back__back__21, FIFO_Head_B_38_end_back__B_39_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core0 > Core4
    receiveEnd(0, 4); // Core0 > Core4
    fifoPush(back__back__33, FIFO_Head_B_15_end_back__B_16_init_feed__0, 1, NULL, 0); // 1 * char
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

