/**
 * @file Core7.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core7 (ID=7).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_20_end_back__B_21_init_feed__0; // FIFO_Head_B_20_end_back > B_21_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__5;  // B_21_init_feed_feed > B_21_0_feed size:= 1*uchar defined in Core0
extern char *const B_21_init_feed__B_21_0__0;  // B_21_init_feed > B_21_0 size:= 1*char defined in Core0
extern char *const FIFO_Head_OB_0_end_back__OB_1_init_feed__0; // FIFO_Head_OB_0_end_back > OB_1_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__25;  // OB_1_init_feed_feed > OB_1_0_feed size:= 1*uchar defined in Core0
extern char *const OB_1_init_feed__OB_1_0__0;  // OB_1_init_feed > OB_1_0 size:= 1*char defined in Core0
extern char *const B_20_init_feed__B_20_0__0;  // B_20_init_feed > B_20_0 size:= 1*char defined in Core0
extern char *const frk_0__B_20_0__0;  // frk_0 > B_20_0 size:= 1*char defined in Core0
extern uchar *const newPort20_20__inB__0;  // frk_0_newPort20_20 > B_20_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__4;  // B_20_init_feed_feed > B_20_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_0__0;  // B_20_0_outB > implode_OC_5_inC_inC_0 size:= 1*uchar defined in Core0
extern uchar *const back__back__3;  // B_20_0_back > B_20_end_back_back size:= 1*uchar defined in Core0
extern char *const B_20_0__implode_OC_5_inC__0;  // B_20_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern char *const B_27_init_feed__B_27_0__0;  // B_27_init_feed > B_27_0 size:= 1*char defined in Core0
extern char *const frk_0__B_27_0__0;  // frk_0 > B_27_0 size:= 1*char defined in Core0
extern uchar *const newPort27_27__inB__0;  // frk_0_newPort27_27 > B_27_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__11;  // B_27_init_feed_feed > B_27_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1__1;  // B_27_0_outB > implode_OC_6_inC_inC_1 size:= 1*uchar defined in Core0
extern uchar *const back__back__10;  // B_27_0_back > B_27_end_back_back size:= 1*uchar defined in Core0
extern char *const B_27_0__B_27_end_back__0;  // B_27_0 > B_27_end_back size:= 1*char defined in Core0
extern char *const B_27_0__implode_OC_6_inC__0;  // B_27_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern char *const B_34_init_feed__B_34_0__0;  // B_34_init_feed > B_34_0 size:= 1*char defined in Core0
extern char *const frk_0__B_34_0__0;  // frk_0 > B_34_0 size:= 1*char defined in Core0
extern uchar *const newPort34_34__inB__0;  // frk_0_newPort34_34 > B_34_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__18;  // B_34_init_feed_feed > B_34_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_2__2;  // B_34_0_outB > implode_OC_7_inC_inC_2 size:= 1*uchar defined in Core0
extern uchar *const back__back__17;  // B_34_0_back > B_34_end_back_back size:= 1*uchar defined in Core0
extern char *const B_34_0__B_34_end_back__0;  // B_34_0 > B_34_end_back size:= 1*char defined in Core0
extern char *const B_34_0__implode_OC_7_inC__0;  // B_34_0 > implode_OC_7_inC size:= 1*char defined in Core0
extern char *const OB_0_0__OB_0_end_back__0;  // OB_0_0 > OB_0_end_back size:= 1*char defined in Core0
extern uchar *const back__back__24;  // OB_0_0_back > OB_0_end_back_back size:= 1*uchar defined in Core0

void* computationThread_Core7(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_20_end_back__B_21_init_feed__0, 1, NULL, 0); // 1 * char
  fifoInit(FIFO_Head_OB_0_end_back__OB_1_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__5, FIFO_Head_B_20_end_back__B_21_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(7, 8); // Core7 > Core8
    sendEnd(); // Core7 > Core8
    fifoPop(feed__feed__25, FIFO_Head_OB_0_end_back__OB_1_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(7, 15); // Core7 > Core15
    sendEnd(); // Core7 > Core15
    receiveStart(); // Core5 > Core7
    receiveEnd(5, 7); // Core5 > Core7
    receiveStart(); // Core0 > Core7
    receiveEnd(0, 7); // Core0 > Core7
    B(newPort20_20__inB__0, feed__feed__4, outB__inC_0__0, back__back__3); // B_20_0

    sendStart(7, 3); // Core7 > Core3
    sendEnd(); // Core7 > Core3
    receiveStart(); // Core13 > Core7
    receiveEnd(13, 7); // Core13 > Core7
    receiveStart(); // Core0 > Core7
    receiveEnd(0, 7); // Core0 > Core7
    B(newPort27_27__inB__0, feed__feed__11, outB__inC_1__1, back__back__10); // B_27_0

    sendStart(7, 14); // Core7 > Core14
    sendEnd(); // Core7 > Core14
    sendStart(7, 2); // Core7 > Core2
    sendEnd(); // Core7 > Core2
    receiveStart(); // Core20 > Core7
    receiveEnd(20, 7); // Core20 > Core7
    receiveStart(); // Core0 > Core7
    receiveEnd(0, 7); // Core0 > Core7
    B(newPort34_34__inB__0, feed__feed__18, outB__inC_2__2, back__back__17); // B_34_0

    sendStart(7, 21); // Core7 > Core21
    sendEnd(); // Core7 > Core21
    sendStart(7, 2); // Core7 > Core2
    sendEnd(); // Core7 > Core2
    fifoPush(back__back__3, FIFO_Head_B_20_end_back__B_21_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core14 > Core7
    receiveEnd(14, 7); // Core14 > Core7
    fifoPush(back__back__24, FIFO_Head_OB_0_end_back__OB_1_init_feed__0, 1, NULL, 0); // 1 * char
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

