/**
 * @file Core10.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core10 (ID=10).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_23_end_back__B_24_init_feed__0; // FIFO_Head_B_23_end_back > B_24_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__8;  // B_24_init_feed_feed > B_24_0_feed size:= 1*uchar defined in Core0
extern char *const B_24_init_feed__B_24_0__0;  // B_24_init_feed > B_24_0 size:= 1*char defined in Core0
extern char *const FIFO_Head_OB_3_end_back__OB_4_init_feed__0; // FIFO_Head_OB_3_end_back > OB_4_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__28;  // OB_4_init_feed_feed > OB_4_0_feed size:= 1*uchar defined in Core0
extern char *const OB_4_init_feed__OB_4_0__0;  // OB_4_init_feed > OB_4_0 size:= 1*char defined in Core0
extern char *const B_23_init_feed__B_23_0__0;  // B_23_init_feed > B_23_0 size:= 1*char defined in Core0
extern char *const frk_0__B_23_0__0;  // frk_0 > B_23_0 size:= 1*char defined in Core0
extern uchar *const newPort23_23__inB__0;  // frk_0_newPort23_23 > B_23_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__7;  // B_23_init_feed_feed > B_23_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_3__0;  // B_23_0_outB > implode_OC_5_inC_inC_3 size:= 1*uchar defined in Core0
extern uchar *const back__back__6;  // B_23_0_back > B_23_end_back_back size:= 1*uchar defined in Core0
extern char *const B_23_0__implode_OC_5_inC__0;  // B_23_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern char *const B_30_init_feed__B_30_0__0;  // B_30_init_feed > B_30_0 size:= 1*char defined in Core0
extern char *const frk_0__B_30_0__0;  // frk_0 > B_30_0 size:= 1*char defined in Core0
extern uchar *const newPort30_30__inB__0;  // frk_0_newPort30_30 > B_30_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__14;  // B_30_init_feed_feed > B_30_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_4__1;  // B_30_0_outB > implode_OC_6_inC_inC_4 size:= 1*uchar defined in Core0
extern uchar *const back__back__13;  // B_30_0_back > B_30_end_back_back size:= 1*uchar defined in Core0
extern char *const B_30_0__B_30_end_back__0;  // B_30_0 > B_30_end_back size:= 1*char defined in Core0
extern char *const B_30_0__implode_OC_6_inC__0;  // B_30_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern char *const B_37_init_feed__B_37_0__0;  // B_37_init_feed > B_37_0 size:= 1*char defined in Core0
extern char *const frk_0__B_37_0__0;  // frk_0 > B_37_0 size:= 1*char defined in Core0
extern uchar *const newPort37_37__inB__0;  // frk_0_newPort37_37 > B_37_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__21;  // B_37_init_feed_feed > B_37_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_5__2;  // B_37_0_outB > implode_OC_7_inC_inC_5 size:= 1*uchar defined in Core0
extern uchar *const back__back__20;  // B_37_0_back > B_37_end_back_back size:= 1*uchar defined in Core0
extern char *const B_37_0__B_37_end_back__0;  // B_37_0 > B_37_end_back size:= 1*char defined in Core0
extern char *const B_37_0__implode_OC_7_inC__0;  // B_37_0 > implode_OC_7_inC size:= 1*char defined in Core0
extern char *const OB_3_0__OB_3_end_back__0;  // OB_3_0 > OB_3_end_back size:= 1*char defined in Core0
extern uchar *const back__back__26;  // OB_3_0_back > OB_3_end_back_back size:= 1*uchar defined in Core0

void* computationThread_Core10(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_23_end_back__B_24_init_feed__0, 1, NULL, 0); // 1 * char
  fifoInit(FIFO_Head_OB_3_end_back__OB_4_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__8, FIFO_Head_B_23_end_back__B_24_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(10, 11); // Core10 > Core11
    sendEnd(); // Core10 > Core11
    fifoPop(feed__feed__28, FIFO_Head_OB_3_end_back__OB_4_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(10, 18); // Core10 > Core18
    sendEnd(); // Core10 > Core18
    receiveStart(); // Core9 > Core10
    receiveEnd(9, 10); // Core9 > Core10
    receiveStart(); // Core0 > Core10
    receiveEnd(0, 10); // Core0 > Core10
    B(newPort23_23__inB__0, feed__feed__7, outB__inC_3__0, back__back__6); // B_23_0

    sendStart(10, 3); // Core10 > Core3
    sendEnd(); // Core10 > Core3
    receiveStart(); // Core16 > Core10
    receiveEnd(16, 10); // Core16 > Core10
    receiveStart(); // Core0 > Core10
    receiveEnd(0, 10); // Core0 > Core10
    B(newPort30_30__inB__0, feed__feed__14, outB__inC_4__1, back__back__13); // B_30_0

    sendStart(10, 17); // Core10 > Core17
    sendEnd(); // Core10 > Core17
    sendStart(10, 2); // Core10 > Core2
    sendEnd(); // Core10 > Core2
    receiveStart(); // Core23 > Core10
    receiveEnd(23, 10); // Core23 > Core10
    receiveStart(); // Core0 > Core10
    receiveEnd(0, 10); // Core0 > Core10
    B(newPort37_37__inB__0, feed__feed__21, outB__inC_5__2, back__back__20); // B_37_0

    sendStart(10, 2); // Core10 > Core2
    sendEnd(); // Core10 > Core2
    sendStart(10, 2); // Core10 > Core2
    sendEnd(); // Core10 > Core2
    fifoPush(back__back__6, FIFO_Head_B_23_end_back__B_24_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core17 > Core10
    receiveEnd(17, 10); // Core17 > Core10
    fifoPush(back__back__26, FIFO_Head_OB_3_end_back__OB_4_init_feed__0, 1, NULL, 0); // 1 * char
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

