/**
 * @file Core17.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core17 (ID=17).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif
extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_30_end_back__B_31_init_feed__0; // FIFO_Head_B_30_end_back > B_31_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__15;  // B_31_init_feed_feed > B_31_0_feed size:= 1*uchar defined in Core0
extern char *const B_31_init_feed__B_31_0__0;  // B_31_init_feed > B_31_0 size:= 1*char defined in Core0
extern char *const OB_3_init_feed__OB_3_0__0;  // OB_3_init_feed > OB_3_0 size:= 1*char defined in Core0
extern char *const frk_0__OB_3_0__0;  // frk_0 > OB_3_0 size:= 2*char defined in Core0
extern uchar *const newPort_3_43__inB__0;  // frk_0_newPort_3_43 > OB_3_0_inB size:= 2*uchar defined in Core0
extern uchar *const feed__feed__27;  // OB_3_init_feed_feed > OB_3_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1__4;  // OB_3_0_outB > implode_OC_9_inC_inC_1 size:= 2*uchar defined in Core0
extern uchar *const back__back__26;  // OB_3_0_back > OB_3_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_3_0__OB_3_end_back__0;  // OB_3_0 > OB_3_end_back size:= 1*char defined in Core0
extern char *const OB_3_0__implode_OC_9_inC__0;  // OB_3_0 > implode_OC_9_inC size:= 2*char defined in Core0
extern char *const B_30_0__B_30_end_back__0;  // B_30_0 > B_30_end_back size:= 1*char defined in Core0
extern uchar *const back__back__13;  // B_30_0_back > B_30_end_back_back size:= 1*uchar defined in Core0
extern char *const implode_OC_9_inC__OC_9__0;  // implode_OC_9_inC > OC_9 size:= 6*char defined in Core0
extern uchar *const outB__inC__4;  // implode_OC_9_inC_outB > OC_9_inC size:= 6*uchar defined in Core0

void* computationThread_Core17(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_outB__inC__4;
	PREESM_MD5_Init(&preesm_md5_ctx_outB__inC__4);
#endif
  // Initialisation(s)

  fifoInit(FIFO_Head_B_30_end_back__B_31_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__15, FIFO_Head_B_30_end_back__B_31_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(17, 11); // Core17 > Core11
    sendEnd(); // Core17 > Core11
    receiveStart(); // Core9 > Core17
    receiveEnd(9, 17); // Core9 > Core17
    receiveStart(); // Core0 > Core17
    receiveEnd(0, 17); // Core0 > Core17
    B(newPort_3_43__inB__0, feed__feed__27, outB__inC_1__4, back__back__26); // OB_3_0

    sendStart(17, 10); // Core17 > Core10
    sendEnd(); // Core17 > Core10
    sendStart(17, 15); // Core17 > Core15
    sendEnd(); // Core17 > Core15
    receiveStart(); // Core10 > Core17
    receiveEnd(10, 17); // Core10 > Core17
    fifoPush(back__back__13, FIFO_Head_B_30_end_back__B_31_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core15 > Core17
    receiveEnd(15, 17); // Core15 > Core17
    C(outB__inC__4); // OC_9
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_outB__inC__4,(char *)outB__inC__4, 6);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_outB__inC__4);
	printf("preesm_md5_outB__inC__4 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

