/**
 * @file Core1.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core1 (ID=1).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_0_end_back__B_1_init_feed__0; // FIFO_Head_B_0_end_back > B_1_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__0;  // B_1_init_feed_feed > B_1_0_feed size:= 1*uchar defined in Core0
extern char *const B_1_init_feed__B_1_0__0;  // B_1_init_feed > B_1_0 size:= 1*char defined in Core0
extern char *const B_2_init_feed__B_2_0__0;  // B_2_init_feed > B_2_0 size:= 1*char defined in Core0
extern char *const frk_0__B_2_0__0;  // frk_0 > B_2_0 size:= 1*char defined in Core0
extern uchar *const newPort2_02__inB__0;  // frk_0_newPort2_02 > B_2_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__1;  // B_2_init_feed_feed > B_2_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_0__5;  // B_2_0_outB > implode_OC_2_inC_inC_0 size:= 1*uchar defined in Core0
extern uchar *const back__feed__0;  // B_2_0_back > B_3_0_feed size:= 1*uchar defined in Core0
extern char *const frk_0__B_3_0__0;  // frk_0 > B_3_0 size:= 1*char defined in Core0
extern uchar *const newPort3_03__inB__0;  // frk_0_newPort3_03 > B_3_0_inB size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1__5;  // B_3_0_outB > implode_OC_2_inC_inC_1 size:= 1*uchar defined in Core0
extern uchar *const back__feed__2;  // B_3_0_back > B_4_0_feed size:= 1*uchar defined in Core0
extern char *const B_3_0__B_4_0__0;  // B_3_0 > B_4_0 size:= 1*char defined in Core0
extern char *const B_0_0__B_0_end_back__0;  // B_0_0 > B_0_end_back size:= 1*char defined in Core0
extern uchar *const back__back__1;  // B_0_0_back > B_0_end_back_back size:= 1*uchar defined in Core0
extern char *const explode_OC_init_inC_inC__implode_OC_1_inC__0; // explode_OC_init_inC_inC > implode_OC_1_inC size:= 4*char defined in Core0
extern char *const B_1_0__implode_OC_1_inC__0;  // B_1_0 > implode_OC_1_inC size:= 1*char defined in Core0
extern char *const B_0_0__implode_OC_1_inC__0;  // B_0_0 > implode_OC_1_inC size:= 1*char defined in Core0
extern uchar *const inC_1__inC_0__0; // explode_OC_init_inC_inC_inC_1 > implode_OC_1_inC_inC_0 size:= 4*uchar defined in Core0
extern uchar *const outB__inC_1_0_1__0;  // B_0_0_outB > implode_OC_1_inC_inC_1_0_1 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1_1_1__0;  // B_1_0_outB > implode_OC_1_inC_inC_1_1_1 size:= 1*uchar defined in Core0
extern uchar *const inC__inC__1;  // implode_OC_1_inC_inC > OC_1_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_1_inC__OC_1__0;  // implode_OC_1_inC > OC_1 size:= 6*char defined in Core0
extern char *const B_4_0__implode_OC_2_inC__0;  // B_4_0 > implode_OC_2_inC size:= 1*char defined in Core0
extern char *const B_5_0__implode_OC_2_inC__0;  // B_5_0 > implode_OC_2_inC size:= 1*char defined in Core0
extern char *const B_6_0__implode_OC_2_inC__0;  // B_6_0 > implode_OC_2_inC size:= 1*char defined in Core0
extern char *const B_7_0__implode_OC_2_inC__0;  // B_7_0 > implode_OC_2_inC size:= 1*char defined in Core0
extern uchar *const outB__inC_2__5;  // B_4_0_outB > implode_OC_2_inC_inC_2 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_3__4;  // B_5_0_outB > implode_OC_2_inC_inC_3 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_4__3;  // B_6_0_outB > implode_OC_2_inC_inC_4 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_5__3;  // B_7_0_outB > implode_OC_2_inC_inC_5 size:= 1*uchar defined in Core0
extern uchar *const outB__inC__5;  // implode_OC_2_inC_outB > OC_2_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_2_inC__OC_2__0;  // implode_OC_2_inC > OC_2 size:= 6*char defined in Core0
extern char *const B_8_0__implode_OC_3_inC__0;  // B_8_0 > implode_OC_3_inC size:= 1*char defined in Core0
extern char *const B_9_0__implode_OC_3_inC__0;  // B_9_0 > implode_OC_3_inC size:= 1*char defined in Core0
extern char *const B_10_0__implode_OC_3_inC__0;  // B_10_0 > implode_OC_3_inC size:= 1*char defined in Core0
extern char *const B_11_0__implode_OC_3_inC__0;  // B_11_0 > implode_OC_3_inC size:= 1*char defined in Core0
extern char *const B_12_0__implode_OC_3_inC__0;  // B_12_0 > implode_OC_3_inC size:= 1*char defined in Core0
extern char *const B_13_0__implode_OC_3_inC__0;  // B_13_0 > implode_OC_3_inC size:= 1*char defined in Core0
extern uchar *const outB__inC_0__7;  // B_8_0_outB > implode_OC_3_inC_inC_0 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_1__7;  // B_9_0_outB > implode_OC_3_inC_inC_1 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_2__7;  // B_10_0_outB > implode_OC_3_inC_inC_2 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_3__6;  // B_11_0_outB > implode_OC_3_inC_inC_3 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_4__5;  // B_12_0_outB > implode_OC_3_inC_inC_4 size:= 1*uchar defined in Core0
extern uchar *const outB__inC_5__5;  // B_13_0_outB > implode_OC_3_inC_inC_5 size:= 1*uchar defined in Core0
extern uchar *const outB__inC__7;  // implode_OC_3_inC_outB > OC_3_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_3_inC__OC_3__0;  // implode_OC_3_inC > OC_3 size:= 6*char defined in Core0

void* computationThread_Core1(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_0_end_back__B_1_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__0, FIFO_Head_B_0_end_back__B_1_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(1, 0); // Core1 > Core0
    sendEnd(); // Core1 > Core0
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    B(newPort2_02__inB__0, feed__feed__1, outB__inC_0__5, back__feed__0); // B_2_0

    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    B(newPort3_03__inB__0, back__feed__0, outB__inC_1__5, back__feed__2); // B_3_0

    sendStart(1, 0); // Core1 > Core0
    sendEnd(); // Core1 > Core0
    receiveStart(); // Core2 > Core1
    receiveEnd(2, 1); // Core2 > Core1
    fifoPush(back__back__1, FIFO_Head_B_0_end_back__B_1_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core5 > Core1
    receiveEnd(5, 1); // Core5 > Core1
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    receiveStart(); // Core2 > Core1
    receiveEnd(2, 1); // Core2 > Core1
    // Join implode_OC_1_inC

    {
    }
    sendStart(1, 14); // Core1 > Core14
    sendEnd(); // Core1 > Core14
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    // Join implode_OC_2_inC

    {
    }
    sendStart(1, 14); // Core1 > Core14
    sendEnd(); // Core1 > Core14
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    receiveStart(); // Core0 > Core1
    receiveEnd(0, 1); // Core0 > Core1
    // Join implode_OC_3_inC

    {
    }
    sendStart(1, 14); // Core1 > Core14
    sendEnd(); // Core1 > Core14
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

