/**
 * @file Core9.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core9 (ID=9).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_22_end_back__B_23_init_feed__0; // FIFO_Head_B_22_end_back > B_23_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__7;  // B_23_init_feed_feed > B_23_0_feed size:= 1*uchar defined in Core0
extern char *const B_23_init_feed__B_23_0__0;  // B_23_init_feed > B_23_0 size:= 1*char defined in Core0
extern char *const FIFO_Head_OB_2_end_back__OB_3_init_feed__0; // FIFO_Head_OB_2_end_back > OB_3_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__27;  // OB_3_init_feed_feed > OB_3_0_feed size:= 1*uchar defined in Core0
extern char *const OB_3_init_feed__OB_3_0__0;  // OB_3_init_feed > OB_3_0 size:= 1*char defined in Core0
extern char *const B_22_init_feed__B_22_0__0;  // B_22_init_feed > B_22_0 size:= 1*char defined in Core0
extern char *const frk_0__B_22_0__0;  // frk_0 > B_22_0 size:= 1*char defined in Core0
extern uchar *const newPort22_22__inB__0;  // frk_0_newPort22_22 > B_22_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__6;  // B_22_init_feed_feed > B_22_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_2__0;  // B_22_0_outB > implode_OC_5_inC_inC_2 size:= 1*uchar defined in Core0
extern uchar *const back__back__5;  // B_22_0_back > B_22_end_back_back size:= 1*uchar defined in Core0
extern char *const B_22_0__implode_OC_5_inC__0;  // B_22_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern char *const B_29_init_feed__B_29_0__0;  // B_29_init_feed > B_29_0 size:= 1*char defined in Core0
extern char *const frk_0__B_29_0__0;  // frk_0 > B_29_0 size:= 1*char defined in Core0
extern uchar *const newPort29_29__inB__0;  // frk_0_newPort29_29 > B_29_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__13;  // B_29_init_feed_feed > B_29_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_3__1;  // B_29_0_outB > implode_OC_6_inC_inC_3 size:= 1*uchar defined in Core0
extern uchar *const back__back__12;  // B_29_0_back > B_29_end_back_back size:= 1*uchar defined in Core0
extern char *const B_29_0__B_29_end_back__0;  // B_29_0 > B_29_end_back size:= 1*char defined in Core0
extern char *const B_29_0__implode_OC_6_inC__0;  // B_29_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern char *const B_36_init_feed__B_36_0__0;  // B_36_init_feed > B_36_0 size:= 1*char defined in Core0
extern char *const frk_0__B_36_0__0;  // frk_0 > B_36_0 size:= 1*char defined in Core0
extern uchar *const newPort36_36__inB__0;  // frk_0_newPort36_36 > B_36_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__20;  // B_36_init_feed_feed > B_36_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_4__2;  // B_36_0_outB > implode_OC_7_inC_inC_4 size:= 1*uchar defined in Core0
extern uchar *const back__back__19;  // B_36_0_back > B_36_end_back_back size:= 1*uchar defined in Core0
extern char *const B_36_0__B_36_end_back__0;  // B_36_0 > B_36_end_back size:= 1*char defined in Core0
extern char *const B_36_0__implode_OC_7_inC__0;  // B_36_0 > implode_OC_7_inC size:= 1*char defined in Core0
extern char *const OB_2_0__OB_2_end_back__0;  // OB_2_0 > OB_2_end_back size:= 1*char defined in Core0
extern uchar *const back__back__25;  // OB_2_0_back > OB_2_end_back_back size:= 1*uchar defined in Core0

void* computationThread_Core9(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_22_end_back__B_23_init_feed__0, 1, NULL, 0); // 1 * char
  fifoInit(FIFO_Head_OB_2_end_back__OB_3_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__7, FIFO_Head_B_22_end_back__B_23_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(9, 10); // Core9 > Core10
    sendEnd(); // Core9 > Core10
    fifoPop(feed__feed__27, FIFO_Head_OB_2_end_back__OB_3_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(9, 17); // Core9 > Core17
    sendEnd(); // Core9 > Core17
    receiveStart(); // Core8 > Core9
    receiveEnd(8, 9); // Core8 > Core9
    receiveStart(); // Core0 > Core9
    receiveEnd(0, 9); // Core0 > Core9
    B(newPort22_22__inB__0, feed__feed__6, outB__inC_2__0, back__back__5); // B_22_0

    sendStart(9, 3); // Core9 > Core3
    sendEnd(); // Core9 > Core3
    receiveStart(); // Core15 > Core9
    receiveEnd(15, 9); // Core15 > Core9
    receiveStart(); // Core0 > Core9
    receiveEnd(0, 9); // Core0 > Core9
    B(newPort29_29__inB__0, feed__feed__13, outB__inC_3__1, back__back__12); // B_29_0

    sendStart(9, 16); // Core9 > Core16
    sendEnd(); // Core9 > Core16
    sendStart(9, 2); // Core9 > Core2
    sendEnd(); // Core9 > Core2
    receiveStart(); // Core22 > Core9
    receiveEnd(22, 9); // Core22 > Core9
    receiveStart(); // Core0 > Core9
    receiveEnd(0, 9); // Core0 > Core9
    B(newPort36_36__inB__0, feed__feed__20, outB__inC_4__2, back__back__19); // B_36_0

    sendStart(9, 23); // Core9 > Core23
    sendEnd(); // Core9 > Core23
    sendStart(9, 2); // Core9 > Core2
    sendEnd(); // Core9 > Core2
    fifoPush(back__back__5, FIFO_Head_B_22_end_back__B_23_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core16 > Core9
    receiveEnd(16, 9); // Core16 > Core9
    fifoPush(back__back__25, FIFO_Head_OB_2_end_back__OB_3_init_feed__0, 1, NULL, 0); // 1 * char
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

