/**
 * @file Core15.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core15 (ID=15).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif
extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_28_end_back__B_29_init_feed__0; // FIFO_Head_B_28_end_back > B_29_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__13;  // B_29_init_feed_feed > B_29_0_feed size:= 1*uchar defined in Core0
extern char *const B_29_init_feed__B_29_0__0;  // B_29_init_feed > B_29_0 size:= 1*char defined in Core0
extern char *const OB_1_init_feed__OB_1_0__0;  // OB_1_init_feed > OB_1_0 size:= 1*char defined in Core0
extern char *const frk_0__OB_1_0__0;  // frk_0 > OB_1_0 size:= 2*char defined in Core0
extern uchar *const newPort_1_40__inB__0;  // frk_0_newPort_1_40 > OB_1_0_inB size:= 2*uchar defined in Core0
extern uchar *const feed__feed__25;  // OB_1_init_feed_feed > OB_1_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_3__3;  // OB_1_0_outB > implode_OC_8_inC_inC_3 size:= 2*uchar defined in Core0
extern uchar *const back__back__23;  // OB_1_0_back > OB_1_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_1_0__OB_1_end_back__0;  // OB_1_0 > OB_1_end_back size:= 1*char defined in Core0
extern char *const OB_1_0__implode_OC_8_inC__0;  // OB_1_0 > implode_OC_8_inC size:= 2*char defined in Core0
extern char *const B_28_0__B_28_end_back__0;  // B_28_0 > B_28_end_back size:= 1*char defined in Core0
extern uchar *const back__back__11;  // B_28_0_back > B_28_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_2_0__implode_OC_9_inC__0;  // OB_2_0 > implode_OC_9_inC size:= 2*char defined in Core0
extern char *const OB_3_0__implode_OC_9_inC__0;  // OB_3_0 > implode_OC_9_inC size:= 2*char defined in Core0
extern char *const OB_4_0__implode_OC_9_inC__0;  // OB_4_0 > implode_OC_9_inC size:= 2*char defined in Core0
extern uchar *const outB__inC_0__4;  // OB_2_0_outB > implode_OC_9_inC_inC_0 size:= 2*uchar defined in Core0
extern uchar *const outB__inC_1__4;  // OB_3_0_outB > implode_OC_9_inC_inC_1 size:= 2*uchar defined in Core0
extern uchar *const outB__inC_2__4;  // OB_4_0_outB > implode_OC_9_inC_inC_2 size:= 2*uchar defined in Core0
extern uchar *const outB__inC__4;  // implode_OC_9_inC_outB > OC_9_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_9_inC__OC_9__0;  // implode_OC_9_inC > OC_9 size:= 6*char defined in Core0
extern char *const implode_OC_5_inC__OC_5__0;  // implode_OC_5_inC > OC_5 size:= 6*char defined in Core0
extern uchar *const outB__inC__0;  // implode_OC_5_inC_outB > OC_5_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_6_inC__OC_6__0;  // implode_OC_6_inC > OC_6 size:= 6*char defined in Core0
extern uchar *const outB__inC__1;  // implode_OC_6_inC_outB > OC_6_inC size:= 6*uchar defined in Core0
extern char *const implode_OC_7_inC__OC_7__0;  // implode_OC_7_inC > OC_7 size:= 6*char defined in Core0
extern uchar *const outB__inC__2;  // implode_OC_7_inC_outB > OC_7_inC size:= 6*uchar defined in Core0

void* computationThread_Core15(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_outB__inC__0;
	PREESM_MD5_Init(&preesm_md5_ctx_outB__inC__0);
	PREESM_MD5_CTX preesm_md5_ctx_outB__inC__1;
	PREESM_MD5_Init(&preesm_md5_ctx_outB__inC__1);
	PREESM_MD5_CTX preesm_md5_ctx_outB__inC__2;
	PREESM_MD5_Init(&preesm_md5_ctx_outB__inC__2);
#endif
  // Initialisation(s)

  fifoInit(FIFO_Head_B_28_end_back__B_29_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__13, FIFO_Head_B_28_end_back__B_29_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(15, 9); // Core15 > Core9
    sendEnd(); // Core15 > Core9
    receiveStart(); // Core7 > Core15
    receiveEnd(7, 15); // Core7 > Core15
    receiveStart(); // Core0 > Core15
    receiveEnd(0, 15); // Core0 > Core15
    B(newPort_1_40__inB__0, feed__feed__25, outB__inC_3__3, back__back__23); // OB_1_0

    sendStart(15, 8); // Core15 > Core8
    sendEnd(); // Core15 > Core8
    sendStart(15, 3); // Core15 > Core3
    sendEnd(); // Core15 > Core3
    receiveStart(); // Core8 > Core15
    receiveEnd(8, 15); // Core8 > Core15
    fifoPush(back__back__11, FIFO_Head_B_28_end_back__B_29_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core16 > Core15
    receiveEnd(16, 15); // Core16 > Core15
    receiveStart(); // Core17 > Core15
    receiveEnd(17, 15); // Core17 > Core15
    receiveStart(); // Core18 > Core15
    receiveEnd(18, 15); // Core18 > Core15
    // Join implode_OC_9_inC

    {
    }
    sendStart(15, 17); // Core15 > Core17
    sendEnd(); // Core15 > Core17
    receiveStart(); // Core3 > Core15
    receiveEnd(3, 15); // Core3 > Core15
    C(outB__inC__0); // OC_5
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_outB__inC__0,(char *)outB__inC__0, 6);
		#endif

    receiveStart(); // Core2 > Core15
    receiveEnd(2, 15); // Core2 > Core15
    C(outB__inC__1); // OC_6
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_outB__inC__1,(char *)outB__inC__1, 6);
		#endif

    receiveStart(); // Core2 > Core15
    receiveEnd(2, 15); // Core2 > Core15
    C(outB__inC__2); // OC_7
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_outB__inC__2,(char *)outB__inC__2, 6);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_outB__inC__0);
	printf("preesm_md5_outB__inC__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_outB__inC__1);
	printf("preesm_md5_outB__inC__1 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_outB__inC__2);
	printf("preesm_md5_outB__inC__2 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

