/**
 * @file Core11.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core11 (ID=11).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_24_end_back__B_25_init_feed__0; // FIFO_Head_B_24_end_back > B_25_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__9;  // B_25_init_feed_feed > B_25_0_feed size:= 1*uchar defined in Core0
extern char *const B_25_init_feed__B_25_0__0;  // B_25_init_feed > B_25_0 size:= 1*char defined in Core0
extern char *const B_24_init_feed__B_24_0__0;  // B_24_init_feed > B_24_0 size:= 1*char defined in Core0
extern char *const frk_0__B_24_0__0;  // frk_0 > B_24_0 size:= 1*char defined in Core0
extern uchar *const newPort24_24__inB__0;  // frk_0_newPort24_24 > B_24_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__8;  // B_24_init_feed_feed > B_24_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_4__0;  // B_24_0_outB > implode_OC_5_inC_inC_4 size:= 1*uchar defined in Core0
extern uchar *const back__back__7;  // B_24_0_back > B_24_end_back_back size:= 1*uchar defined in Core0
extern char *const B_24_0__implode_OC_5_inC__0;  // B_24_0 > implode_OC_5_inC size:= 1*char defined in Core0
extern char *const B_31_init_feed__B_31_0__0;  // B_31_init_feed > B_31_0 size:= 1*char defined in Core0
extern char *const frk_0__B_31_0__0;  // frk_0 > B_31_0 size:= 1*char defined in Core0
extern uchar *const newPort31_31__inB__0;  // frk_0_newPort31_31 > B_31_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__15;  // B_31_init_feed_feed > B_31_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_5__1;  // B_31_0_outB > implode_OC_6_inC_inC_5 size:= 1*uchar defined in Core0
extern uchar *const back__back__14;  // B_31_0_back > B_31_end_back_back size:= 1*uchar defined in Core0
extern char *const B_31_0__B_31_end_back__0;  // B_31_0 > B_31_end_back size:= 1*char defined in Core0
extern char *const B_31_0__implode_OC_6_inC__0;  // B_31_0 > implode_OC_6_inC size:= 1*char defined in Core0
extern char *const B_38_init_feed__B_38_0__0;  // B_38_init_feed > B_38_0 size:= 1*char defined in Core0
extern char *const frk_0__B_38_0__0;  // frk_0 > B_38_0 size:= 1*char defined in Core0
extern uchar *const newPort38_38__inB__0;  // frk_0_newPort38_38 > B_38_0_inB size:= 1*uchar defined in Core0
extern uchar *const feed__feed__22;  // B_38_init_feed_feed > B_38_0_feed size:= 1*uchar defined in Core0
extern uchar *const outB__inC_0__3;  // B_38_0_outB > implode_OC_8_inC_inC_0 size:= 1*uchar defined in Core0
extern uchar *const back__back__21;  // B_38_0_back > B_38_end_back_back size:= 1*uchar defined in Core0
extern char *const B_38_0__B_38_end_back__0;  // B_38_0 > B_38_end_back size:= 1*char defined in Core0
extern char *const B_38_0__implode_OC_8_inC__0;  // B_38_0 > implode_OC_8_inC size:= 1*char defined in Core0

void* computationThread_Core11(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_24_end_back__B_25_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__9, FIFO_Head_B_24_end_back__B_25_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(11, 12); // Core11 > Core12
    sendEnd(); // Core11 > Core12
    receiveStart(); // Core10 > Core11
    receiveEnd(10, 11); // Core10 > Core11
    receiveStart(); // Core0 > Core11
    receiveEnd(0, 11); // Core0 > Core11
    B(newPort24_24__inB__0, feed__feed__8, outB__inC_4__0, back__back__7); // B_24_0

    sendStart(11, 3); // Core11 > Core3
    sendEnd(); // Core11 > Core3
    receiveStart(); // Core17 > Core11
    receiveEnd(17, 11); // Core17 > Core11
    receiveStart(); // Core0 > Core11
    receiveEnd(0, 11); // Core0 > Core11
    B(newPort31_31__inB__0, feed__feed__15, outB__inC_5__1, back__back__14); // B_31_0

    sendStart(11, 18); // Core11 > Core18
    sendEnd(); // Core11 > Core18
    sendStart(11, 2); // Core11 > Core2
    sendEnd(); // Core11 > Core2
    receiveStart(); // Core2 > Core11
    receiveEnd(2, 11); // Core2 > Core11
    receiveStart(); // Core0 > Core11
    receiveEnd(0, 11); // Core0 > Core11
    B(newPort38_38__inB__0, feed__feed__22, outB__inC_0__3, back__back__21); // B_38_0

    sendStart(11, 4); // Core11 > Core4
    sendEnd(); // Core11 > Core4
    sendStart(11, 3); // Core11 > Core3
    sendEnd(); // Core11 > Core3
    fifoPush(back__back__7, FIFO_Head_B_24_end_back__B_25_init_feed__0, 1, NULL, 0); // 1 * char
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

