/**
 * @file Core20.c
 * @generated by CPrinter
 * @date Thu May 25 15:09:14 CEST 2023
 *
 * Code generated for processing element Core20 (ID=20).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

extern char Shared[312]; //  size:= 312*char
extern char *const FIFO_Head_B_33_end_back__B_34_init_feed__0; // FIFO_Head_B_33_end_back > B_34_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__18;  // B_34_init_feed_feed > B_34_0_feed size:= 1*uchar defined in Core0
extern char *const B_34_init_feed__B_34_0__0;  // B_34_init_feed > B_34_0 size:= 1*char defined in Core0
extern char *const FIFO_Head_OB_4_end_back__OB_5_init_feed__0; // FIFO_Head_OB_4_end_back > OB_5_init_feed size:= 1*char defined in Core0
extern uchar *const feed__feed__29;  // OB_5_init_feed_feed > OB_5_0_feed size:= 1*uchar defined in Core0
extern char *const frk_0__OB_5_0__0;  // frk_0 > OB_5_0 size:= 2*char defined in Core0
extern uchar *const newPort_5_45__inB__0;  // frk_0_newPort_5_45 > OB_5_0_inB size:= 2*uchar defined in Core0
extern uchar *const outB__out_0__0;  // OB_5_0_outB > implode_jn_end_out_out_out_0 size:= 2*uchar defined in Core0
extern uchar *const back__back__28;  // OB_5_0_back > OB_5_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_5_0__OB_5_end_back__0;  // OB_5_0 > OB_5_end_back size:= 1*char defined in Core0
extern char *const B_33_0__B_33_end_back__0;  // B_33_0 > B_33_end_back size:= 1*char defined in Core0
extern uchar *const back__back__16;  // B_33_0_back > B_33_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_4_0__OB_4_end_back__0;  // OB_4_0 > OB_4_end_back size:= 1*char defined in Core0
extern uchar *const back__back__27;  // OB_4_0_back > OB_4_end_back_back size:= 1*uchar defined in Core0
extern char *const OB_6_0__implode_jn_end_out_out__0;  // OB_6_0 > implode_jn_end_out_out size:= 2*char defined in Core0
extern char *const OB_7_0__implode_jn_end_out_out__0;  // OB_7_0 > implode_jn_end_out_out size:= 2*char defined in Core0
extern char *const OB_8_0__implode_jn_end_out_out__0;  // OB_8_0 > implode_jn_end_out_out size:= 2*char defined in Core0
extern char *const OB_9_0__implode_jn_end_out_out__0;  // OB_9_0 > implode_jn_end_out_out size:= 2*char defined in Core0
extern uchar *const outB__out_1__0;  // OB_6_0_outB > implode_jn_end_out_out_out_1 size:= 2*uchar defined in Core0
extern uchar *const outB__out_2__0;  // OB_7_0_outB > implode_jn_end_out_out_out_2 size:= 2*uchar defined in Core0
extern uchar *const outB__out_3__0;  // OB_8_0_outB > implode_jn_end_out_out_out_3 size:= 2*uchar defined in Core0
extern uchar *const outB__out_4__0;  // OB_9_0_outB > implode_jn_end_out_out_out_4 size:= 2*uchar defined in Core0
extern uchar *const outB__out__0;  // implode_jn_end_out_out_outB > jn_end_out_out size:= 10*uchar defined in Core0
extern char *const implode_jn_end_out_out__jn_end_out__0; // implode_jn_end_out_out > jn_end_out size:= 10*char defined in Core0

void* computationThread_Core20(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

  // Initialisation(s)

  fifoInit(FIFO_Head_B_33_end_back__B_34_init_feed__0, 1, NULL, 0); // 1 * char
  fifoInit(FIFO_Head_OB_4_end_back__OB_5_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__18, FIFO_Head_B_33_end_back__B_34_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(20, 7); // Core20 > Core7
    sendEnd(); // Core20 > Core7
    fifoPop(feed__feed__29, FIFO_Head_OB_4_end_back__OB_5_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core0 > Core20
    receiveEnd(0, 20); // Core0 > Core20
    B(newPort_5_45__inB__0, feed__feed__29, outB__out_0__0, back__back__28); // OB_5_0

    sendStart(20, 21); // Core20 > Core21
    sendEnd(); // Core20 > Core21
    receiveStart(); // Core13 > Core20
    receiveEnd(13, 20); // Core13 > Core20
    fifoPush(back__back__16, FIFO_Head_B_33_end_back__B_34_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core18 > Core20
    receiveEnd(18, 20); // Core18 > Core20
    fifoPush(back__back__27, FIFO_Head_OB_4_end_back__OB_5_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core21 > Core20
    receiveEnd(21, 20); // Core21 > Core20
    receiveStart(); // Core22 > Core20
    receiveEnd(22, 20); // Core22 > Core20
    receiveStart(); // Core23 > Core20
    receiveEnd(23, 20); // Core23 > Core20
    receiveStart(); // Core19 > Core20
    receiveEnd(19, 20); // Core19 > Core20
    // Join implode_jn_end_out_out

    {
    }
    sendStart(20, 5); // Core20 > Core5
    sendEnd(); // Core20 > Core5
    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

  return NULL;
}

